apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-example-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-example-k8s
  template:
    metadata:
      name: nestjs-example-k8s
      labels:
        app: nestjs-example-k8s
    spec:
      containers:
        - name: nestjs-docker-for-k8s
          image: yanchespenda/nestjs-docker-for-k8s
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nestjs-example-k8s-service
  labels:
    app: nestjs-example-k8s-service
  annotations:
    dev.okteto.com/generate-host: "true"
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  selector:
    name: nestjs-example-k8s
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000